INSERT INTO COUNTRY_MASTER (COUNTRY_ID,COUNTRY_NAME) values(1,'India');
INSERT INTO COUNTRY_MASTER (COUNTRY_ID,COUNTRY_NAME) values(2,'USA');
INSERT INTO STATE_MASTER (STATE_ID,COUNTRY_ID,STATE_NAME) values(1,1,'Maharashtra');
INSERT INTO STATE_MASTER (STATE_ID,COUNTRY_ID,STATE_NAME) values(2,1,'Karnataka');
INSERT INTO STATE_MASTER (STATE_ID,COUNTRY_ID,STATE_NAME) values(3,2,'New Jersy');
INSERT INTO STATE_MASTER (STATE_ID,COUNTRY_ID,STATE_NAME) values(4,2,'Ohio');
INSERT INTO CITIES_MASTER (CITY_ID,CITY_NAME,STATE_ID) values(1,'Mumbai',1);
INSERT INTO CITIES_MASTER (CITY_ID,CITY_NAME,STATE_ID) values(2,'Pune',1);
INSERT INTO CITIES_MASTER (CITY_ID,CITY_NAME,STATE_ID) values(3,'Banglore',2);
INSERT INTO CITIES_MASTER (CITY_ID,CITY_NAME,STATE_ID) values(4,'Mysore',2);
INSERT INTO CITIES_MASTER (CITY_ID,CITY_NAME,STATE_ID) values(5,'Maywood',3);
INSERT INTO CITIES_MASTER (CITY_ID,CITY_NAME,STATE_ID) values(6,'Westwood',3);
INSERT INTO CITIES_MASTER (CITY_ID,CITY_NAME,STATE_ID) values(7,'Oakwood',4);
INSERT INTO CITIES_MASTER (CITY_ID,CITY_NAME,STATE_ID) values(8,'Cuyahoga Country',4);


